version: "3"

services:
  pre-processing:
    image: nadhirahrafidz98/team_11:preprocess
    volumes:
      - ./init/mysql_data/ml-latest-small:/init/mysql_data/ml-latest-small
      - ./init/mysql_data/personality-isf2018:/init/mysql_data/personality-isf2018
      - ./init/mysql_data/scraped_data:/init/mysql_data/scraped_data
      - ./init/mysql_data/final_data:/init/mysql_data/final_data

  mySQLcontainer:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=MovieLens
      - MYSQL_ROOT_PASSWORD=team11
    volumes:
      - ./init/db_setup:/docker-entrypoint-initdb.d/
      - ./init/mysql_data:/init/data
    command: --secure-file-priv="init/data"
    ports:
      - 3306:3306
    networks:
      - team11net
    depends_on:
      - pre-processing

  websvr_container:
    image: nadhirahrafidz98/team_11:websvr
    deploy:
      replicas: 1
    volumes:
      - ./LAMPcontainer/data:/var/www/html
    ports:
      - 80:80
    networks:
      - team11net
    links:
      - mySQLcontainer
    depends_on:
      - mySQLcontainer


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PMAcontainer
    environment:
      - PMA_HOST=mySQLcontainer
      - MYSQL_ROOT_PASSWORD=team11
      - PMA_PORT=3306
    ports:
      - 8080:80
    networks:
      - team11net

  frontend:
    image: nadhirahrafidz98/team_11:frontend
    deploy:
      replicas: 1
    volumes:
      - "./frontend:/frontend"
    ports:
      - 3000:3000
    networks:
      - team11net
    environment:
      - CHOKIDAR_USEPOLLING=true

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Load balancing
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - websvr_container
    links:
      - frontend
      - websvr_container
    ports:
      - 4000:4000
      - 5000:5000
    networks:
      - team11net

networks:
  team11net:
    name: team11net
