version: "3"

services:
  pre-processing:
    build: .
    volumes:
      - ./init/mysql_data/ml-latest-small:/init/mysql_data/ml-latest-small
      - ./init/mysql_data/personality-isf2018:/init/mysql_data/personality-isf2018
      - ./init/mysql_data/scraped_data:/init/mysql_data/scraped_data
      - ./init/mysql_data/final_data:/init/mysql_data/final_data

  mySQLcontainer:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=team11
    volumes:
      - ./init/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/mysql_data:/init/data
    command: --secure-file-priv="init/data"
    ports:
      - 3306:3306
    depends_on:
      - pre-processing

  websvr_container:
    build: ./LAMPcontainer
    volumes:
      - ./LAMPcontainer/data:/var/www/html
    ports:
      - 80:80
    links:
      - mySQLcontainer
    depends_on:
      - mySQLcontainer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PMAcontainer
    environment:
      - PMA_HOST=mySQLcontainer
      - MYSQL_ROOT_PASSWORD=team11
      - PMA_PORT=3306
    ports:
      - 8080:80

  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/frontend"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
